<?php

namespace AppBundle\Repository;

/**
 * EbayFiltersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EbayFiltersRepository extends \Doctrine\ORM\EntityRepository
{
}
