<?php

namespace AppBundle\Repository;

/**
 * searchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class searchRepository extends \Doctrine\ORM\EntityRepository
{
}
