<?php

namespace AppBundle\Repository;

/**
 * SearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchRepository extends \Doctrine\ORM\EntityRepository
{
	public function countNumberOfSearches(User $user)
    {
        return $this->createQueryBuilder('sc')
            ->andWhere('sc.user = :user')
            ->setParameter('user', $user)
            ->select('COUNT(sc.id) as tally')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
