app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
